FROM python:3.11-slim

WORKDIR /app

# Install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app /app/app

# Start Celery worker
CMD ["celery", "-A", "app.core.scheduler.celery_app", "worker", "--loglevel=info"]